### ISSUE TITLE
Is `Source_Code/__pycache__` necessary?

### ISSUE THREAD

**Issue by luzpaz** [HarryvL/fcFEM-basic#1]
https://github.com/HarryvL/fcFEM-basic/tree/main/Source_Code/__pycache__

**Comment by HarryvL** [comment]
Not necessary. I believe this gets generated by NUMBA to cache compiled code?!

I will delete and add in the .gitignore

**Comment by luzpaz** [comment]
Heads-up, when you make the commit, you can add `Closes #<ticket number>` in the commit summary (doesn't have to be the title) and it will auto-close this ticket

**Comment by HarryvL** [comment]
Thanks
